{-|
Module      : Position
Description : Positional information for the AST
Copyright   : (c) Edward Jones, 2019
License     : GPL-3
Maintainer  : Edward Jones
Stability   : experimental
Portability : POSIX
Language    : Haskell2010

This module defines the machinery to parse the Emperor language from a token stream generated by the Emperor lexer.
-}
module Language.Position
    ( GetPos
    , getPos
    ) where

-- import           Language.AST

import           Language.SpadeLexer (AlexPosn (..), Token, position)

class GetPos a where
    getPos :: a -> AlexPosn -- ^ Return the position in the input stream

instance GetPos Token where
    getPos = position
