name: Continuous Integration
on: pull_request
jobs:
  compile:
    name: Compile source code
    runs-on: ubuntu-latest
    steps:
      - uses: webfactory/ssh-agent@v0.1.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - uses: actions/checkout@v1
        with:
          submodules: recursive
      - name: Run make
        run: make
        id: make
  lint:
    name: Run linter
    runs-on: ubuntu-latest
    needs: [compile]
    steps:
      - uses: webfactory/ssh-agent@v0.1.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - uses: actions/checkout@v1
        with:
          submodules: recursive
      - name: Run hlint
        id: hlint
        run: make lint
  format:
    name: Run code formatter
    runs-on: ubuntu-latest
    needs: [compile]
    steps:
      - uses: webfactory/ssh-agent@v0.1.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - uses: actions/checkout@v1
        with:
          submodules: recursive
      - name: Run stylish-haskell
        id: stylish-haskell
        run: make format
     
