name: Continuous Integration
on: pull_request
jobs:
  compile:
    name: Compile source code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: git submodule init && git submodule update
      - uses: actions/setup-haskell@v1
      - name: Run make
        run: make -B
        id: make
  lint:
    name: Run linter
    runs-on: ubuntu-latest
    needs: [compile]
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: recursive
      - name: Run hlint
        id: hlint
        run: make lint
  format:
    name: Run code formatter
    runs-on: ubuntu-latest
    needs: [compile]
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: recursive
      - name: Run stylish-haskell
        id: stylish-haskell
        run: make format

