name: Continuous Integration
on: pull_request
jobs:
  compile:
    name: Compile source code
    runs-on: ubuntu-latest
    steps:
      - name: Run make
        run: make
        id: make
  lint:
    name: Run linter
    runs-on: ubuntu-latest
    needs: [compile]
    steps:
      - name: Run hlint
        id: hlint
        run: make lint
  format:
    name: Run code formatter
    runs-on: ubuntu-latest
    needs: [compile]
    steps:
      - name: Run stylish-haskell
        id: stylish-haskell
        run: make format
     
